### ISSUE TITLE
React Roadmap: Marked All As Done But Still Showing 99% Done (79 of 80 Done)

### ISSUE THREAD

**Issue by chanyizhe885632** [kamranahmedse/developer-roadmap#9379]
### What is the URL where the issue is happening

https://roadmap.sh/react

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

After marking all items in the React Roadmap as completed, the progress indicator still shows 99% done (79 of 80) instead of reflecting full completion. All items appear marked as “Done,” but the system does not update to 80 of 80 or 100% as expected.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jcanalesluna** [comment]
I've made some changes from the backoffice and it should be fixed now, though it may take some time to be displayed on the web. Thanks for reporting!

**Comment by chanyizhe885632** [comment]
Hi @jcanalesluna, I just checked and it’s still showing “79 of 80 Done”.
