### ISSUE TITLE
[New Roadmap Feedback] Swift & Swift UI roadmap includes no resources

### ISSUE THREAD

**Issue by timothyis** [kamranahmedse/developer-roadmap#9390]
### Roadmap URL

https://roadmap.sh/swift-ui

### Suggestions

The Swift/Swift UI roadmap includes no resources for each point of the roadmap. If Apple have official resources, it would be good to link them into each part (at least, if those inspired the roadmap.)

**Comment by jcanalesluna** [comment]
Thanks for reporting. This should be fixed now :)

**Comment by timothyis** [comment]
Thanks @jcanalesluna, but I think quite a few are still missing. Notably, the introduction and "Swift Basics" items of the path.

**Comment by jcanalesluna** [comment]
It will take some time to be displayed on the web, due to the cache policy. Tomorrow it should be fine

**Comment by timothyis** [comment]
Looks good now, thank you!
